### ISSUE TITLE
Feat: external LDAP as a source of truth

### ISSUE THREAD

**Issue by xeoneox** [sebadob/rauthy#915]
It would be nice if Rauthy supported external sources of truth, such as LDAP. LDAP is not great at being an authentication protocol, but is excellent for a centralized authentication database. LDAP + OIDC is the ideal combination.

**Comment by sebadob** [comment]
We had this question a few times by now.

I don't have any single use case for LDAP and as long as not someone else provides a PR with a complete integration, or an external company requests this as a paid feature, it will not be implemented.

If you need LDAP support, take a look at [kanidm](https://github.com/kanidm/kanidm).

**Comment by xeoneox** [comment]
"I don't have any single use case for LDAP"

S3 policies
PostgreSQL Auth
SMTP/IMAP engines
a query-able authentication source for authentication relationships
PAM

KanIDM sadly hasn't been able to meet my needs.

I will continue to recommend LLDAP with Authelia, but I hope this project will eventually come around when you get a good PR. It's really nice, and I hope it can compete with Authelia eventually.

**Comment by helmut72** [comment]
> Is done on our side via a centralized, self-written cloud service already, which directly talks to the mail server and manages credentials automatically.

Is it possible to explain a bit more about your workflow for new user and how you manage your self hosted mail server with your own domain onh your single source of truth user database, rauthy?

**Comment by sebadob** [comment]
> Is it possible to explain a bit more about your workflow for new user and how you manage your self hosted mail server with your own domain onh your single source of truth user database, rauthy?

Rauthy is the single source of truth for all auth and user related values, not for every existing config value overall. Values that are needed in multiple places or just make sense to save together with a user are stored as custom attributes and managed by Rauthy. 

However, some data is managed in other places, when it's only really necessary over there. For instance in case of Postgres creds, they are auto-generated inside K8s as secrets and never leave the cluster. Whenever another application needs them, they are injected into the pods by referencing the original secret, so they only exist in one place and never leave it.
The same is true for things like E-Mail aliases or catch all addresses. Each user on our side has a main E-Mail address, which is also the reference for Rauthy. Additional ones only exist inside another custom application. Aliases do not exist on the E-Mail server. I think it's just a waste of resources to try to manage them there. Instead, the application has a catch all handler and dynamically checks if any incoming mails should be mapped to a temp alias for a user. These temp emails will not even be saved on the E-Mail server itself. If an alias is needed, it's often once and then only for max 24h.

Since Rauthy `v0.29`, in case of a new user, all we need is a registration on Rauthy. Everything that's necessary afterward is handled fully automatically via SCIM and some custom handlers. Most of the custom logic is inside the cloud app I mentioned. Any user / group updates will be pushed over there via SCIM and it manages the mail server via API calls (create mailboxes, create some custom folders, ...). In other situations, when something does not support SCIM and a registration is necessary or nice to have before the user logs in for the very first time, like e.g. our VPN, it is handled by the cloud app as well. 
If you like more separation, you could also have another client in Rauthy that only maps to an application that handles SCIM events and converts them into API call to custom apps. This client does not even need any login, only manage SCIM updates.

Depending on your mail server, you could also just manage them automatically via SCIM directly. We just want to have some custom logic and a specific mailbox / address naming and additional things, so that it's easier to do this in the other application than to connect the mail server directly.

---

You could use Rauthy as a single source of truth for most of the data via custom attributes. I just think it's better and easier to keep some stuff in even more locked down, not even publicly available locations (like e.g. K8s secrets with private K8s API), if you don't need them anywhere else. These days, I very much always follow the KISS principle.

**Comment by helmut72** [comment]
> in case of Postgres
(...)
> for things like E-Mail aliases

IMHO different usage. 1st one belongs to a service/environment, 2nd belongs to a human/user account.

> some data is managed in other places, when it's only really necessary over there

For example birthday is also stored to a user directory (regardless if it's LDAP or rauthy) even if it is used rarely.

> for things like E-Mail aliases

Also the 2nd mail address belongs to a user!?

> SCIM (...) Most of the custom logic is inside the cloud app I mentioned.

What's the name of this cloud app, how to install? I'm not aware of a mail server right now, that supports SCIM

**Comment by xeoneox** [comment]
I certainly appreciate your enthusiasm and vision. I do however disagree with a K8s solution being simple or having a small attack surface. LDAP would still be my preference. I'm rather fond of both Nomad and Podman Quadlets, so a solution demanding K8s is a non-starter for my auth needs. 

I can completely understand if external sources of truth require a lot of work, and it's not where you'd want to take the project. 

The PAM module sounds very interesting. That would alleviate a lot of my concerns.

**Comment by sebadob** [comment]
> My point is that Kubernetes is not the only way to achieve this, that's a fallacy being imposed on us all right now.

I never said that, of course it's not. I cannot think of any task that can only be solved in one specific way in this regard.

> I just don't wish for projects to require it in the future. 

And again, never said that. Rauthy does not require it at all. You can run it anywhere you like.

> (...) and Kubernetes is too resource heavy to go unchallenged forever.

I fully agree on that one.

> If you promoted this front and center, it would prevent dummies like me from interrupting your work :)

Yeah I did not on purpose, because I don't want to make promises I cannot hold in the end. And, if I publish this, I want it to be working nicely without much trouble. Username + Password is straight forward and no big deal, but I want Webauthn in the terminal, preferrably even with devices that do the authentication via QR code, even though we only use Hardware Passkeys exclusively. Because I don't know yet how nicely this will work, I have not promoted this in any way yet. Generic PAM modules for OIDC / oauth logins exist already, so there is no need to reinvent the wheel, as long as it's not doing anything special.

> Right now, today, with no special knowledge or unproven techniques, I can build a Terraform / [Ignition](https://registry.terraform.io/providers/community-terraform-providers/ignition/latest/docs) / [Ansible](https://registry.terraform.io/providers/ansible/ansible/latest) / [Fedora CoreOS](https://docs.ansible.com/ansible/latest/collections/community/general/rpm_ostree_pkg_module.html) / Nomad solution that is easier to access & comprehend for developers, and is lighter weight, than Kubernetes.

I looked at a stack like this in the past as well, but it was not fully meeting my needs. In fact, I would really like ditching K8s for something lighter weight. I use `k3s` these days most often because we don't manage thousands of servers and it's already a big improvement in terms of resource usage, but I would still like it to be more light weight. One of the biggest reasons for me to create Rauthy in the first place was having something more light weight and faster than Keycloak, which we relied on for years.
The last time I took a look at Nomad was quite a while ago, maybe I should revisit it. The reason we are fully on K8s is that we know it very well, it is super solid and just gets the job done. We will migrate to probably a new environment in a couple of months and if there is something better, I would ditch K8s immediately. I am not a fanboy at all, I use whatever gets the job done in the (for me) best way in a specific situation. Right now, it's managing config maps and secrets inside K8s, because it's there anyway already.

**Comment by DanielRamosAcosta** [comment]
Hi! I think I have a use case here, although I’m not sure if there’s another way to solve it. I’m trying to set up SSO for the services I have on my NAS, and I’m considering using Rauthy. The problem is that I’d like to keep using Samba to access the files, and it would be great if the SSO password could be the same as the Samba password.

The only option I can think of is setting up an SSO that uses OpenLDAP as a backend, which the Samba server would also point to.

I’ve been looking into this project, but it seems that without using LDAP as the source of truth, it would be impossible... or not?

Do you have any ideas on how to use Rauthy with Samba without having to rely on LDAP?

Thanks a lot, and best regards!

**Comment by sebadob** [comment]
I don't know much about samba, since I don't use Windows and in our entire company, not a single person is on Windows.

> The problem is that I’d like to keep using Samba to access the files, and it would be great if the SSO password could be the same as the Samba password.

That would be convenient, but sounds like a terrible idea from a security standpoint imho. Samba is known for quite a few vulerabilities, especially older implementations. In fact, you should never re-use the same password in different environments. I don't know how the setup with samba + ldap would be done, but if it would not forward the login to ldap but "copy" the password into the samba config, that would be terrible.

> I’ve been looking into this project, but it seems that without using LDAP as the source of truth, it would be impossible... or not?

Don't know if any OIDC "adapters" or proxies exist, but if not, probably impossible. If it's possible to add your own custom auth hook to samba, you could, with a tiny script, use a client with `password` flow maybe, but I am the wrong person to ask for advice here, since I don't rely on samba at all. However, the `password` flow should only be used if you can trust the client app 100%, because it will see the users SSO password during the login.

**Comment by DanielRamosAcosta** [comment]
In my case, I still have some Windows systems that I need to support. Yes, after doing some research, I think I will finally drop Samba entirely and explore other alternatives, like WebDAV or NFS.

Thank you very much for your response anyway @sebadob!

**Comment by xeoneox** [comment]
> In my case, I still have some Windows systems that I need to support. Yes, after doing some research, I think I will finally drop Samba entirely and explore other alternatives, like WebDAV or NFS.

There's a hundred corner cases like this where PAM would be a great alternative to direct LDAP queries. Is there an ETA on when Rauthy will have the PAM module available? Is it on the roadmap?

**Comment by sebadob** [comment]
There is no ETA, but I did first successful PAM login tests with a local Yubikey today. This is a very early version though and I used `pamtester` for this, not a real machine yet. In this very early version, it is also limited to USB Passkeys only. However, this is a pretty big step in a good direction. 

Hardware keys will of course only work for local logins (without installing additional software, which I don't want to require). I need to either figure out a nice way for remote logins with MFA, or leave these password only for the first public tests. Don't know yet. Quite a bit of work is stil left to make it really usable though and until then, you could use any OIDC pam module out there.

**Comment by sebadob** [comment]
fyi, the PAM feature has its own issue now: #1107

**Comment by sebadob** [comment]
I would say since the whole PAM module has been finished and will be released with the next version, this issue can be closed. The likelihood that anyone will need LDAP with the new features is very small and it's almost non-existent for the case that anyone else will do the complete implementation for an LDAP backend.

I anyone really wants to contribute all this work at some point, the issue could be re-opened.
