### ISSUE TITLE
Validation on Authorization Request `state` Parameter Too Strict

### ISSUE THREAD

**Issue by dotsam** [sebadob/rauthy#974]
**Describe the bug**
Trying to set up Proxmox to authenticate with rauthy, I get a Payload validation error when attempting to authenticate

**To Reproduce**
1. Create a new client in rauthy with the default paremeters
2. Configure Proxmox to use the client
3. Attempt to authenticate in Proxmox with the rauthy client
4. Receive the error message instead of the expected login flow

**Expected behavior**
Authentication should proceed and succeed

The full error received is:
```
{"timestamp":1748827900,"error":"BadRequest","message":"Payload validation error: ValidationErrors({\"state\": Field([ValidationError { code: \"[a-zA-Z0-9,.:/_-&?=~#!$'()*+%]+$\", message: None, params: {\"value\": String(\"{\\\"csrf_token\\\":\\\"gEg-SiZbU3BieqdGS623eA\\\",\\\"realm\\\":\\\"rauthy\\\"}\")} }])})"}
```

The URL that Proxmox is redirecting to is:
```
https://RAUTHYDOMAIN/auth/v1/oidc/authorize?response_type=code&client_id=proxmox&state=%7B%22csrf_token%22%3A%22gEg-SiZbU3BieqdGS623eA%22%2C%22realm%22%3A%22rauthy%22%7D&code_challenge=NoHA7M9KKQm10LY024ePXQGxKvlSZwfW65MAnZurddw&code_challenge_method=S256&redirect_uri=https%3A%2F%2FPROXYMOXDOMAIN%3A8006&scope=openid+email+profile+groups&nonce=vEAtPBfcqWHQCeP1LOnoCw&display=page
```

So it looks like Proxmox is trying to pass a JSON string as it's `state`, and rauthy is rejecting it.

Rauthy currently does the following validation for `state`:
https://github.com/sebadob/rauthy/blob/550b7eeb5d0125c901dbe49a9c43cc3ac70e84a0/src/api_types/src/oidc.rs#L51-L53

Reading from the spec at https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1, the state is defined as "An opaque value", and further in the appendix (https://datatracker.ietf.org/doc/html/rfc6749#appendix-A.5) it's spec'd to be a "VSCHAR", which is defined as the byte-range `%x20-7E`

So I think that rauthy needs to relax its validation for state to allow the full unicode range defined in the spec, especially since this is an "opaque" value that rauthy should really only be passing back untouched.

**Comment by sebadob** [comment]
That's not working as intended. The regex defines all URL safe characters and when I test the given `state` against that regex manually, everything is fine. Yes it's opaque, but since passed in a URL, the idea was that only URL safe characters make sense anyway.

This is probably a bug / interaction issue between `validator` and `actix-web`. It looks like the URL safe chars are converted before the validation, which then will of course make the whole validation fail.

I will fix this and probably just put a length constraint on the state to avoid resource exhaustion attacks.

Edit: 

Btw this was working before and it seems, that "something" did a silent change under the hood. -.-
Thanks!

**Comment by sebadob** [comment]
The main issue was, that the UI was URL decoding the state and then submitted it as it was. This is usually not a problem, because a JSON in a URL is very often problematic and even browsers treat it differently, so it should have been base64 encoded. However, I updated the UI to always make sure when submitting, that this value is URL encoded properly.

The original validation was just fine, because values must be URL encoded, even though the state is opaque. It was just that the UI  was doing something wrong. Fixed in the next release.

**Comment by dotsam** [comment]
Great, thanks so much for the quick turnaround on this, looking forward to the next release!

**Comment by dotsam** [comment]
Testing with v0.30.0, this still doesn't seem to be fixed for me. Same exact error. To confirm, clicking the "log in" button in the application redirects me to the rauthy URL mentioned in the original report, and the error appears right away, so I think this is erroring in the GET handler, not the UI or the POST handler.

**Comment by sebadob** [comment]
That's very werid, because I even added your example `state` to the integration tests, and they are fine. I also did manual tests from different browsers to make sure the value is okay.

> and the error appears right away

This means you get an error page before even seeing inputs for email / password?

Edit:

Do you have the same result with different browser engines?

**Comment by sebadob** [comment]
I could of course just remove the validation for URL safe characters and only limit the length, which would probably fix it right away, but I would like to understand what exactly is going wrong here. For instance, when you go to https://rustexp.lpil.uk/ and paste the regex being used `^[a-zA-Z0-9,.:/_\-&?=~#!$'()*+%]+$` and then test against your `state` param `%7B%22csrf_token%22%3A%22gEg-SiZbU3BieqdGS623eA%22%2C%22realm%22%3A%22rauthy%22%7D`, it's just fine.

Edit: 

Found a way to reproduce it. I will have another look. Sorry.

**Comment by sebadob** [comment]
I built a nightly image for you. Please have a look with this one: `ghcr.io/sebadob/rauthy:0.30.2-20250613`

It only constraints by length and limits the state param to max 2048 characters. The web framework is doing some automatic conversions under the hood and depending on at which point I am doing the validation, the values might be different.

It now also makes sense, why the integration tests are fine, because they skip the `GET` endpoint, since they don't use a browser but direct requests.

**Comment by dotsam** [comment]
Thanks, I can confirm the nightly image gets me through the auth flow and back to the application, but the application is giving me an authorization error, so I might need to tweak the client config or disable some of the stricter rauthy defaults.

**Comment by sebadob** [comment]
That's good news. The first thing is probably to change the token alg's to `RS256`, because that's the only alg a lot of clients support, unfortunately. However, if it's because of the `state`, and it may not be able to deserialize it because the framework maybe did something "bad" to it, that would be important to know.

**Comment by dotsam** [comment]
Changing the token algorithms worked! I'm happy to keep testing further versions if you need it.

**Comment by sebadob** [comment]
Yay, that's nice to hear, thanks!

I will wait a few days if some other small bugs appear and will then release a new stable patch next week probably. But you can keep on using the nightly image. It's safe to do, as it does not contain any DB migrations.

It would be super cool if you could add your Proxmox setup to the docs when I (probably also next week) add an example configs section in the book with a template.

**Comment by sebadob** [comment]
Fyi you should upgrade to stable `ghcr.io/sebadob/rauthy:0.30.2`. The nightly cannot be pulled anymore.
